[theme]
primaryColor = "#F2F2F2"
backgroundColor = "#050505"
secondaryBackgroundColor = "#131313"
textColor = "#F2F2F2"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
